name: Build personal website
run-name: ${{ github.actor }} is creating a build 🚀
on:
    push:
      branches: [main]
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '20'

     - name: Run npm install
       run: npm install

     - name: upload project
       run: actions/upload-pages-artifact

     - name: Deploy to Github pages
       run: actions/deploy-pages@v4
       
       
    


