name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'
            registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: build project
        run: yarn predeploy

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: dist

     

