name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Yarn Install
        shell: bash
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn run predeploy 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Replace with your GitHub access token stored in repository secrets
          BRANCH: gh-pages  # Branch to deploy to
          FOLDER: dist  # Folder containing your built website files
